language: php
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.5
      env:
        - PHPUNIT_VERSION=^4.8
        - LARAVEL_VERSION=5.2.*
    - php: 5.6
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^5.7
        - LARAVEL_VERSION=5.2.*
    - php: 5.6
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^5.7
        - LARAVEL_VERSION=5.3.*
    - php: 5.6
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^5.7
        - LARAVEL_VERSION=5.4.*
    - php: 7.0
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^5.7
        - LARAVEL_VERSION=5.4.*
    - php: 7.0
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^6.0
        - LARAVEL_VERSION=5.5.*
    - php: 7.1
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^6.0
        - LARAVEL_VERSION=5.5.*
    - php: 7.1
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^7.5
        - LARAVEL_VERSION=5.6.*
    - php: 7.1
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^7.5
        - LARAVEL_VERSION=5.7.*
    - php: 7.1
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^7.5
        - LARAVEL_VERSION=5.8.*
    - php: 7.2
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^6.0
        - LARAVEL_VERSION=5.5.*
    - php: 7.2
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^7.5
        - LARAVEL_VERSION=5.6.*
    - php: 7.2
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^7.5
        - LARAVEL_VERSION=5.7.*
    - php: 7.2
      env:
        - COVERAGE=1 XDEBUG=1
        - PHPUNIT_VERSION=^7.5
        - LARAVEL_VERSION=5.8.*
  fast_finish: true

before_script:
  - curl --version
  - php --version
  - travis_retry composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --dev --no-update -n
  - travis_retry composer require "laravel/framework:${LARAVEL_VERSION}" --no-update -n
  - travis_retry composer install --no-suggest --prefer-dist -n -o
  - if [[ "$TRAVIS_PHP_VERSION" != "7.0" || "$TRAVIS_PHP_VERSION" != "7.1" ]]; then echo "xdebug.overload_var_dump = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini || true; fi

script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then vendor/bin/phpunit --verbose --coverage-text --coverage-clover build/logs/clover.xml; fi

after_success:
  bash <(curl -s https://codecov.io/bash)
